theme: minima
title: Cinema Persona
author: clariceism
description: > # this means to ignore newlines until "baseurl:"
  Creating 100 UX User Personas based on characters in mainstream movies.

# social links
github_username:  clariceism # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
